# Generated by Django 2.1.4 on 2018-12-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='temperature',
            field=models.FloatField(),
        ),
    ]
